### PR TITLE
Increase wait timeout for keyclock and cert-manager

### LINKED ISSUE #75: increase retry count or sleep time
Some steps inside the deploy-deps scripts tend to fail randomly on retry. We might need to increase the retry count or increase the sleep time.

### PR DESCRIPTION
**Pull request by avi-biton**
Increase wait timeout for `keyclock` and `cert-manager` by 1 minute

fix #75

### CODE REVIEW

File: deploy-deps.sh [hunk 1]
```diff
@@ -86,7 +86,7 @@ deploy_tekton() {
 
 deploy_cert_manager() {
     kubectl apply -k "${script_path}/dependencies/cert-manager"
-    retry "kubectl wait --for=condition=Ready --timeout=120s -l app.kubernetes.io/instance=cert-manager -n cert-manager pod" \
+    retry "kubectl wait --for=condition=Ready --timeout=180s -l app.kubernetes.io/instance=cert-manager -n cert-manager pod" \
```
Comment (yftacherzog) [inline deploy-deps.sh]: This won't address the issue with cert-manager. It was failing not because the timeout was reached, but because the pod was not created after 3 x sleep time allowed by the retry function.

Comment (yftacherzog) [reply deploy-deps.sh]: (I don't have a good solution to this issue)

Comment (avi-biton) [reply deploy-deps.sh]: In this case we can increase the number of retries, or the sleep between retries

Comment (yftacherzog) [reply deploy-deps.sh]: This will apply to any retry we do. Not sure that we want that. It might be that, instead, we can sleep a little before this retry to reduce the chance of this happening. This should not cost us anything if we assume that the retry will either iterate more than once or the pod will take some time to be ready.

Comment (avi-biton) [reply deploy-deps.sh]: We can use a parameter for how many retries we want, it involves changes to the retry and all the uses of it.
Or as you mentioned we can add sleep before the retry, something like:
```
retry() {

    for _ in {1..3}; do
        sleep 3
        local ret=0
        $1 || ret="$?"
        if [[ "$ret" -eq 0 ]]; then
            return 0
        fi
    done

    echo "$1": "$2."
    return "$ret"
}
```

Comment (yftacherzog) [reply deploy-deps.sh]: I meant adding a sleep before the retry is called specifically for the case of cert-manger. I don't think it will have any cost in terms of execution time for the entire script - it will just move the waiting for an earlier stage.

Yes. We can also introduce a new arg to the retry function as you mentioned.

Comment (avi-biton) [reply deploy-deps.sh]: Done (adding sleep before the retry)

**Review by yftacherzog — APPROVED** [review]
lgtm
